CREATE TABLE worker (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(1000) NOT NULL CONSTRAINT namechk CHECK(char_length(name) >= 2),
    BIRTHDAY DATE CHECK(BIRTHDAY > '1900-01-01'),
    LEVEL VARCHAR NOT NULL CHECK(LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK(SALARY > 100 AND SALARY < 100000) 

);

CREATE TABLE client (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(1000) NOT NULL CONSTRAINT namechk CHECK(char_length(name) >= 2)
);

CREATE TABLE project (
    ID INT GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID  INT,
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE project_worker(
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY (PROJECT_ID,WORKER_ID)

)
